name = "chaos-guile-api"
main = "workers/printful-api.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
# PRINTFUL_API_KEY = "your-printful-api-key"
# PRINTFUL_WEBHOOK_SECRET = "your-webhook-secret"

[env.development.vars]
# PRINTFUL_API_KEY = "your-development-api-key"
# PRINTFUL_WEBHOOK_SECRET = "your-development-webhook-secret"

# Routes for the worker
[[routes]]
pattern = "chaosandguile.com/api/*"
zone_name = "chaosandguile.com"

# For development
[[routes]]
pattern = "*.chaosandguile.pages.dev/api/*"