name = "chaos-guile-api"
main = "workers/printful-api.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
# PRINTFUL_API_KEY = "your-printful-api-key"
# PRINTFUL_WEBHOOK_SECRET = "your-webhook-secret"
# STRIPE_SECRET_KEY = "your-stripe-secret-key"

[env.development.vars]
# PRINTFUL_API_KEY = "your-development-api-key"
# PRINTFUL_WEBHOOK_SECRET = "your-development-webhook-secret"
# STRIPE_SECRET_KEY = "your-development-stripe-secret-key"

# Routes will be configured in Cloudflare dashboard
# Uncomment and configure these when you have chaosandguile.com domain:
# [[routes]]
# pattern = "chaosandguile.com/api/*"
# zone_name = "chaosandguile.com"